// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wycieczka.Context;

namespace Wycieczka.Migrations
{
    [DbContext(typeof(WycieczkaDbContext))]
    [Migration("20210122120621_initdb1")]
    partial class initdb1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Wycieczka.Models.WycieczkaInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ilosc_Km")
                        .HasColumnType("float");

                    b.Property<int>("Liczba_Dni")
                        .HasColumnType("int");

                    b.Property<string>("Miejsce_Docelowe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miejsce_Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url_Filmu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url_Zdj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("WycieczkaInfos");
                });

            modelBuilder.Entity("Wycieczka.Models.zdjecia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Url_zdj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WycieczkaInfoID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WycieczkaInfoID");

                    b.ToTable("Zdjecias");
                });

            modelBuilder.Entity("Wycieczka.Models.zdjecia", b =>
                {
                    b.HasOne("Wycieczka.Models.WycieczkaInfo", "WycieczkaInfo")
                        .WithMany("Zdjecias")
                        .HasForeignKey("WycieczkaInfoID");

                    b.Navigation("WycieczkaInfo");
                });

            modelBuilder.Entity("Wycieczka.Models.WycieczkaInfo", b =>
                {
                    b.Navigation("Zdjecias");
                });
#pragma warning restore 612, 618
        }
    }
}
